### ISSUE TITLE
type of sampling 3 or 1 ?

### ISSUE THREAD

**Issue by samieti02** [deepmedic/deepmedic#174]
Hello my dear Sir ,

About the type of sampling, if you just have 2 classes, class 0 = non tumor or background and class 1 = tumor or foreground (or 2 classes for tumor and non tumor), there would not be a difference between typeOfSamplingForTraining = 0 and typeOfSamplingForTraining = 3 or which type would be better in this case?
How can we process more the class1, by setting the value `proportionOfSamplesToExtractPerCategoryTraining = [0.3, 0.7]` like this, for type = 3 OR
`proportionOfSamplesToExtractPerCategoryTraining = [0.7, 0.3]` like this, for type = 1 ?

Because I have Flair and T1 modalities and for Flair, i have a score of 70% and for T1 50%. I try now differents settings. Is it also possible that you integrate the mean accuracy over all epochs for the training ?
Does it play a role, if i want to improve the results?

Thanks
Sami

**Comment by Kamnitsask** [comment]
Hi Sami,

Types of sampling:

Background VS Foreground:
typeOfSamplingForTraining = 0
proportionOfSamplesToExtractPerCategoryTraining = [0.3, 0.7] 
The above will take 30% of samples from background (label==0) and 70% from foreground (merge all labels >0 into one, and that's the foreground). Works quite well for tumors. percentages 30/70 are adjustable ofcourse. Trial and error till you achieve what you wish.

Uniform:
typeOfSamplingForTraining = 1
proportionOfSamplesToExtractPerCategoryTraining = None # not appicable.
This takes all samples in a uniform way throughout the image. Randomly, with uniform (equal) probability from anywhere within the ROI mask (eg your brainmask).

Each class separately:
typeOfSamplingForTraining = 3
proportionOfSamplesToExtractPerCategoryTraining = [0.6, 0.3, 0.1] 
(assuming 3 classes, background + 2 others) This will sample 60% background (lbl=0), 30% label 1, 10% label 2.

If you have 2 classes only (eg background=0, tumor=1), then:
sampling type=0
proportion = [ X, Y]
is equal to
sampling type = 3
proportion = [X, Y]

Sampling type = 1 is completely different.

I did not get how T1 & Flair channels are related to sampling. The input channels have nothing to do with it.

**Comment by samieti02** [comment]
Hi Kamnitsask,

thanks for the explanations. Regarding the code , I think you mean 

```
typeOfSamplingForTraining = 0
proportionOfSamplesToExtractPerCategoryTraining = [0.7, 03]
```

instead of

```
typeOfSamplingForTraining = 0
proportionOfSamplesToExtractPerCategoryTraining = [0.3, 0.7]
```

That means e.g., trying with `proportionOfSamplesToExtractPerCategoryTraining = [0.8, 0.2]` , 20% of samples from background (label==0) and 80% from foreground (tumor, label==1), will give more focus on tumor.
My data has more images after surgery. Therefore, it would also be good to have more focus on the tumor, as the tumor is not always easy to recognize or has not grown well.

**Comment by Kamnitsask** [comment]
Yes, you are correct. It was my mistake above.

When:
```
typeOfSamplingForTraining = 0
```
then in the 2-numbers list given to:
```
proportionOfSamplesToExtractPerCategoryTraining = [0.7, 03]
```
The first number is FOREground (eg tumor for you), the second number is BACKground (label==0). Opposite of what I had said.

I editted my above reply to not confuse next readers.

Thanks.
