### ISSUE TITLE
Plot animation of detection of tumor over epochs/time

### ISSUE THREAD

**Issue by samieti02** [deepmedic/deepmedic#176]
Hello dear Sir,

is there a way to plot an animation and see how the data trained over the epochs or to see how the tumor in brain is being detected (also in the test phase)? 
I am not a big expert in matplot, this is why im asking about how it would be possible to achieve that.

Thanks

**Comment by Kamnitsask** [comment]
Belated reply:

Such a feature is not a priority for DM, as it's not a widely needed, and can be produced by the user according to his/her needs.

DM saves a checkpoint very training epoch. You would need to run a forward pass (test) on the images of interest, with the checkpoints you are interested in.

If we were to create such a plot by default, we would need to be saving all predictions at each step/epoch/whatever, which would take too much space. Not a priority feature for now.
