### ISSUE TITLE
Segment-size (input) error

### ISSUE THREAD

**Issue by samieti02** [deepmedic/deepmedic#178]
Hello Sir,

i have some questions about an this error
```

ERROR: [in function checkRecFieldVsSegmSize()] : The segment-size (input) should be at least as big as the receptive field of the model! This was not found to hold! Dimensions of Receptive Field: [41, 41, 41] . Dimensions of Segment:  [29, 29, 29]

ERROR: The segment-size (input) should be at least as big as the receptive field of the model! The network was made with a receptive field of dimensions:  [41, 41, 41] . But in the case of : TRAINING  the dimensions of the input segment were specified smaller:  [29, 29, 29] . Please fix this by adjusting number of layer and kernel dimensions! Exiting!
```

I had the size
segmentsDimTrain = [29,29,29]
segmentsDimVal = [25,25,25]
segmentsDimInference = [40,40,40]

In my previous test, everything works well, then I added some layers and got this error. Why does it happen and how can we avoid that?

Thanks

**Comment by adnama547** [comment]
When you added layers, the convolutions use more pixels from the original image so your receptive field is bigger. But you kept your segment sizes smaller than the receptive field. You can get some idea of receptive field size using a calculator like this: https://fomoro.com/research/article/receptive-field-calculator
