### ISSUE TITLE
Testing error

### ISSUE THREAD

**Issue by chenxiaodanhit** [deepmedic/deepmedic#180]
Hi @Kamnitsask ,
    I have trained sucessfully, but when i was testing, It turns out that 
`exception when trying to load parameters from the given path of a previously saved model
` 
  I checked my training input and testing input to ensure that they have same size. Could you give me some advice? Thank you!

**Comment by Kamnitsask** [comment]
Hi,

Can you provide more details? Can you copy paste the exact message, and a little bit above to see where this came from?

**Comment by chenxiaodanhit** [comment]
Hi @Kamnitsask ,
This is the wrong place!
![image](https://user-images.githubusercontent.com/46680345/61877906-7ea4f700-af22-11e9-80cd-7197ec9dce7b.png)

**Comment by chenxiaodanhit** [comment]
Hi @Kamnitsask ,
Thank you for your patience! This is the error information.
![image](https://user-images.githubusercontent.com/46680345/61878138-05f26a80-af23-11e9-8c1e-387503493079.png)

**Comment by chenxiaodanhit** [comment]
Hi @Kamnitsask ,
I print the train model and test model, It is different.
The train model is as follows:
![image](https://user-images.githubusercontent.com/46680345/61880555-b3677d00-af27-11e9-9f41-f8bd46e5f0f3.png)
The test model is as follows:
![image](https://user-images.githubusercontent.com/46680345/61880693-ee69b080-af27-11e9-976b-da792cc7c4c2.png)
I don't understand why. Could you give me your sugesstion? Thank you very much.

**Comment by Kamnitsask** [comment]
As the error method says, you are likely trying to use different architecture for testing than what you are trying to load (trained).

The above screenshots confirm this. One is the tiny (toy) model, one is the full deepmedic. You are probably pointing to the wrong modelConfig, either for training or testing.

K

**Comment by chenxiaodanhit** [comment]
Hi @Kamnitsask ,
Than you for your kindness! I successfully trained and tested my data, but when i increase my data size, it turns out this error. could you introduct me? Thank you!
![image](https://user-images.githubusercontent.com/46680345/61994512-bdb38380-b0ad-11e9-8ff8-1176cc7b779c.png)

**Comment by chenxiaodanhit** [comment]
Hi @Kamnitsask ,
Than you for your kindness! I successfully trained and tested my data, but when i increase my data size, it turns out this error. could you introduct me? Thank you!
![image](https://user-images.githubusercontent.com/46680345/61994657-f05e7b80-b0af-11e9-87c0-0ebebd3a931d.png)

**Comment by Kamnitsask** [comment]
Original error has been resolved. Closing this.
(I m guessing the secondary issue has been resolved on the user's end by now)
