### ISSUE TITLE
NaN ValueError encountered during sampling

### ISSUE THREAD

**Issue by Jing-He** [deepmedic/deepmedic#188]
Hi Konstantinos,

Thank you very much for open source deepmedic! We like it a lot!

During training, we came across an error

![image](https://user-images.githubusercontent.com/23385786/67905748-97c7d000-fb2f-11e9-99b2-9d221f7002e8.png)

I worked around it using an early return. 

![image](https://user-images.githubusercontent.com/23385786/67905780-bded7000-fb2f-11e9-98a9-a468fce2e7dd.png)

Do you think this is a correct way to fix it ? Do you have any suggestions ?

Thank you!

**Comment by Kamnitsask** [comment]
Hi Jing-He,

I have run into exactly this problem myself under some settings.

Sampled coordinates should end up None only if the segmentation map (manual) is empty. This is expected, and the calling function should take care of this case. And not sample, nor call this function sample_coords_of_segments, which threw you the error. This is fine, no problem. Error should not happen.

But, I have noticed that this problem/error happens sometimes (not always, random) when I am training with affine-augmentation:
In the trainConfig, the following line is for affine augmentation:
augm_img_prms_tr = {'affine': { 'prob': 0.0, 'max_rot_xyz': (45., 45., 45.), 'max_scaling': 0.1, 'interp_order_imgs': 1 } }

When prob = 0.0, no augm happens. When it's larger than 0, augm with rotation and scaling is done. When I do this, sometimes (random), it can happen.
I am assuming that the rotation/scaling can do something unexpected to some cases.
I still have not identified completely the problem in my settings (when augmentation is done).

But, that being said, I have bypassed it exactly as you have. For now. Until I diagnose and solve it better.

The only problem is: When you do that, you are effectively training on less samples than you would expect (less training iterations).

If it is not happening too often, that's fine. Check your training logs for the message you through in the if statement. If it's not too often, that's fine. It's exactly how I bypass it too for now.

Out of curiosity, it would help me diagnose the problem if we can identify what in your setttings are causing it...
- Have you also turned on this affine-augmentation? (by setting the prob > 0) ?
- Do you have subjects in your training set that have manual-segmentation empty for some classes?
- If you want, it could help me a lot if you could email me the training-config that you used when the error was thrown. Perhaps even the training-logs of the session.
(konstantinos.kamnitsas12@imperial.ac.uk)

**Comment by Kamnitsask** [comment]
On master, after push of 6a3314c to master with v0.8.2
