### ISSUE TITLE
Issue with running DM on Windows

### ISSUE THREAD

**Issue by sarthakpati** [deepmedic/deepmedic#190]
Hi,

I am having some issues running DM on Windows:

```powershell
PS E:\Projects\DeepMedic> E:\Downloads\env_dm\python.exe .\deepMedicRun -model .\examples\configFiles\tinyCnn\model\modelConfig.cfg -train .\examples\configFiles\tinyCnn\train\trainChannels_flair.cfg -dev cuda0
2020-01-28 10:53:27.027412: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
Given configuration file:  E:\Projects\DeepMedic\examples\configFiles\tinyCnn\model\modelConfig.cfg
Given configuration file:  E:\Projects\DeepMedic\examples\configFiles\tinyCnn\train\trainChannels_flair.cfg
Traceback (most recent call last):
  File ".\deepMedicRun", line 146, in <module>
    session = TrainSession( TrainConfig(abs_path_train_cfg) )
  File "E:\Projects\DeepMedic\deepmedic\frontEnd\configParsing\trainConfig.py", line 124, in __init__
    Config.__init__(self, abs_path_to_cfg)
  File "E:\Projects\DeepMedic\deepmedic\frontEnd\configParsing\config.py", line 17, in __init__
    exec(open(self._abs_path_to_cfg).read(), self._configStruct)
  File "<string>", line 1
    ../../../dataForExamples/brats2015TrainingData/train/brats_2013_pat0005_1/Flair_subtrMeanDivStd.nii.gz
    ^
SyntaxError: invalid syntax
```

I have CUDA 10.1 and cuDNN 7.6.5 installed and available on the PATH (and I think TensorFlow is able to pick it up). If you could give some guidance towards fixing this, I'd be grateful.

**Comment by Kamnitsask** [comment]
Invalid python syntax in the above line.
Tries to parse the config file (train config) and gets invalid python syntax within the trainConfig.

Where is that line located?

I believe you have by mistake added a rogue line at the top of your config file.

(nothing to do with CUDA)

**Comment by sarthakpati** [comment]
I believe that it is the config file ```./examples/configFiles/tinyCnn/train/trainChannels_flair.cfg```

I have not made any changes to it.

**Comment by Kamnitsask** [comment]
In your command line, you are passing the wrong file.
The -train option takes as argument the path to a trainConfig.cfg, that has the parameters for training.
You are passing the file that has the paths to the flairs.

**Comment by sarthakpati** [comment]
BOOM! That was it! Totally missed it, thank you. :)
