### ISSUE TITLE
What does trainChannels_t1c mean

### ISSUE THREAD

**Issue by 459737087** [deepmedic/deepmedic#201]
Is that a annotation file or other files?
And What is the difference between gtLabelsTraining and roiMasksTraining？

**Comment by Kamnitsask** [comment]
Hello,

If you open up these files with a text editor, you will see their format, and you will find (by default) paths to corresponding Niftis that we provide for the toy-examples (see main README.md file).
You can have a look at those images with a Niftii editor and this will probably most easily answer any questions regarding those images.

In short, "channels" are input channels, gtLabels are ground-truth (gt) labels (i.e. manual annotations), and roiMasks are region-of-interest (roi) masks (e.g. brainmask in brain segmentation tasks).
You can alter what channels you provide, while roi-mask is optional.

You can find more info about these in the main readme file, and also in the notes within the trainConfig.cfg and testConfig.cfg files.

Kind regards,
