### ISSUE TITLE
3DCRF

### ISSUE THREAD

**Issue by MiguelAngeloMartinsRibeiro** [deepmedic/deepmedic#209]
In the first paper of the documentation they implement a 3D CRF. I couldn't find the implementation in this repo. Is it here?

Thank you

**Comment by Kamnitsask** [comment]
Hello and thank you for your interest in our work.

The CRF is here: https://github.com/deepmedic/dense3dCrf

Thank you very much

**Comment by MiguelAngeloMartinsRibeiro** [comment]
A 2021-04-21 20:39, Konstantinos Kamnitsas escreveu:

> Hello and thank you for your interest in our work. 
> 
> The CRF is here: https://github.com/deepmedic/dense3dCrf 
> 
> Thank you very much 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].

Hi, i don't know if you'll receive this email. Hope everything is ok
with you. Im doing my thesis and I need some help. 

I've been reading and I'm positive that 3DCRF is used for nifti images.
I want to use it as a post-processing tool for masks that I get from a
RGB video segmentation network. The masks I get are binary so I think
instead of changing the code to adapt the best way of using the 3DCRF is
converting this masks into nifti files right? What do you think? I have
0 experience in CRF. 

Regards  

Miguel 

Links:
------
[1]
https://github.com/deepmedic/deepmedic/issues/209#issuecomment-824308245
[2]
