### ISSUE TITLE
list Index out of range

### ISSUE THREAD

**Issue by Yzr0064** [deepmedic/deepmedic#218]
Hi Kamnitsask,
I used BRATS2021 to train the network, but the following errors occurred
TRAIN AND VALIDATION process is done ， but in test 
it showed list index out of range 
ERROR: Caught exception from main process: .list index out of rangeTraceback (most recent call last):
File"/content/drive/MyDrive/y2r/deepmedic/./deepMedicRun"，line 180，in <module>session.run session(sess device， model params)File "/content/drive/MvDrive/v2r/deepmedic/deepmedic/frontEnd/testSession.py", line 97，in run sessioncnn3d.setup ops n feeds to testself. log, inp plchldrs, p y given x, self. params.inds fms per pathtype per layer to savelFile "/content/drive/MyDrive/y2r/deepmedic/deepmedic/neuralnet/cnn3d,py", line 167, in setup ops n feeds to testindicesOfFmsToExtractFromthislayer = indicesOfFmsToVisualisePerlaver0fCertainPathwaylblock iIndexError: list index out of range
can u help me to solve this problem?

**Comment by Kamnitsask** [comment]
Have you un-commented the variable 'saveIndividualFms' in the testConfig? (it is originally commented out). It seems something wrong is happening with it. Can you try testing with it commented out? Also please comment out (if you havent) the variables after it, such as minMaxIndicesOfFmsToSaveFromEachLayerOfNormalPathway, minMaxIndicesOfFmsToSaveFromEachLayerOfSubsampledPathway and minMaxIndicesOfFmsToSaveFromEachLayerOfFullyConnectedPathway.
And let me know what happens then?

(it seems there is some inconsistency between the number of layers  / feature maps of the model, and the number of layers/feature-maps that a variable in the code (e.g. testindicesOfFmsToExtractFromthislayer) expects.

**Comment by sahar90o** [comment]
Hello, 
I also had the same issue when I wanted to test my models. 
As you mentioned, I commented out 'saveIndividualFms' and the next variables. Now it works. Thanks.
