### ISSUE TITLE
Project is missing accurate setup instructions

### ISSUE THREAD

**Issue by alexd2580** [deepmedic/deepmedic#220]
The project does not contain a `requirements.txt` file or a `pyproject.toml` file, making installation inherently difficult. Combined with the complex nature of machine learning applications this completely eliminates reproducibility.

Further combined with the fact that this software depends on features which are deprecated in more modern versions of e.g. numpy it raises the entry barrier even higher.

**Comment by alexd2580** [comment]
e.g. something along the lines of:

```
# Create a python3.7 virtualenv.
python3.7 -m venv venv
# Activate it.
. venv/bin/activate
# Install dependencies.
pip install -r requirements.txt
# Install the package itself.
pip install .
# Run demo.
./deepMedicRun -model ./examples/configFiles/tinyCnn/model/modelConfig.cfg -train examples/configFiles/tinyCnn/train/trainConfigWithValidation.cfg
```

Here's the `requirements.txt` i generated for my probably-working setup, it's actually a freeze-lock, but that's ok too:
```
absl-py==2.1.0
astor==0.8.1
cachetools==4.2.4
certifi==2024.6.2
charset-normalizer==3.3.2
gast==0.2.2
google-auth==1.35.0
google-auth-oauthlib==0.4.6
google-pasta==0.2.0
grpcio==1.62.2
h5py==3.8.0
idna==3.7
importlib-metadata==6.7.0
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.2
Markdown==3.4.4
MarkupSafe==2.1.5
nibabel==4.0.2
numpy==1.21.6
oauthlib==3.2.2
opt-einsum==3.3.0
packaging==24.0
pandas==1.3.5
protobuf==3.19.0
pyasn1==0.5.1
pyasn1-modules==0.3.0
python-dateutil==2.9.0.post0
pytz==2024.1
requests==2.31.0
requests-oauthlib==2.0.0
rsa==4.9
scipy==1.7.3
six==1.16.0
tensorboard==2.0.2
tensorflow==2.0.0
tensorflow-estimator==2.0.1
termcolor==2.3.0
typing_extensions==4.7.1
urllib3==2.0.7
Werkzeug==2.2.3
wrapt==1.16.0
zipp==3.15.0
```

**Comment by Kamnitsask** [comment]
Hello,

The readme contains extensive instructions about how to install the software. The libraries required are in the setup.py, and the instructions in the readme show you how to install / use it.

Have you tried following the steps in the readme? Did you get a specific error? A specific incompatibility with a specific version of a library? If you did, then please let us know about specific incompatible libraries. Without specifics about an issue, it's hard to help. Last time I installed it from scratch was about a year ago, following standard instructions in readme, and all went fine.

Note: This software is 7-8 years old, reproduced by a very big number of works. So, please have a look at readme before stating that the project's status "completely eliminates reproducibility". Especially try to include specifics about errors you encountered when following the described installation steps in the readme please, e.g. if you found specific versions of TF/Numpy/etc incompatible. That would help me in trying to maintain it further with the little time I find nowadays. Thanks!

**Comment by alexd2580** [comment]
No problem, i will gladly post all my findings and errors i encountered when "simply following the readme" shortly :) Thanks for your quick reply!

**Comment by Kamnitsask** [comment]
I had a look at this and re-installed from scratch the project on a new machine, without any issues. I guess an issue you may have had (probably common with users), you may have not had installed versions of Python/TF/cudnn that are compatible with each other. To help users further, I updated the readme with a combination of exact versions of python, Tensorflow and cudnn that work. Other combinations will work too, as long as these 3 are compatible. For different systems and GPU-drivers, other versions may be needed, depending on GPU drivers, so each user should ensure that they make an environment with combinations that are compatible (looking at docs of TF), but the versions I show in readme should be fine for most users in 2024. Closing this issue at this point. Thanks.
